repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/crate-ci/typos'
    rev: v1.28.4
    hooks:
      - id: typos
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.8.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: 'https://github.com/econchick/interrogate'
    rev: 1.7.0
    hooks:
      - id: interrogate
        args:
          # - '-vv'
          - '--quiet'
          - '--fail-under=80'
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
  - repo: https://github.com/twu/skjold
    rev: v0.6.2
    hooks:
      - id: skjold
        name: "skjold: Auditing dependencies for known vulnerabilities."
        entry: skjold audit
        language: python
        language_version: python3
        files: ^(uv.lock)$
