global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['{{cookiecutter.project_slug}}-server:8000']
    metrics_path: '/metrics'
    scrape_interval: 60s  # Reduced frequency: 1 minute instead of 10 seconds

  - job_name: 'keycloak'
    static_configs:
      - targets: ['{{cookiecutter.project_slug}}-keycloak:9000']
    metrics_path: '/metrics'
    scrape_interval: 30s  # Scrape every 30 seconds

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s  # Scrape Traefik metrics every 30 seconds
