services:
  {{cookiecutter.project_slug}}-db:
    image: postgres:13
    hostname: {{cookiecutter.project_slug}}-db
    container_name: {{cookiecutter.project_slug}}-db

    networks:
      - {{cookiecutter.project_slug}}-network

    ports:
      - "5432:5432"

    volumes:
      - postgres-{{cookiecutter.project_slug}}-data:/var/lib/postgresql/data
      {% if cookiecutter.use_keycloak == "y" %}
      - ../db:/docker-entrypoint-initdb.d
      {% endif %}

    env_file:
      - .pg_env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  {% if cookiecutter.use_redis == "y" %}
  {{cookiecutter.project_slug}}-redis:
    image: redis:alpine
    container_name: {{cookiecutter.project_slug}}-redis

    networks:
      - {{cookiecutter.project_slug}}-network

    ports:
      - 6379:6379

    command: redis-server --notify-keyspace-events KEA

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  {% endif %}

  {{cookiecutter.project_slug}}-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: {{cookiecutter.project_slug}}-server
    hostname: {{cookiecutter.project_slug}}-server

    networks:
      - {{cookiecutter.project_slug}}-network

    ports:
      - "8001:8000"

    volumes:
      - .:/project

    user: ${UID}:${GID}

    env_file:
      - .srv_env

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    depends_on:
      hw-db:
        condition: service_healthy
      {% if cookiecutter.use_redis == "y" %}
      hw-redis:
        condition: service_healthy
      {% endif %}
      {% if cookiecutter.use_keycloak == "y" %}
      hw-keycloak:
        condition: service_healthy
      {% endif %}

    # command: sh -c "uvicorn app:application --host 0.0.0.0 --port 8000"

  {% if cookiecutter.use_keycloak == "y" %}
  {{cookiecutter.project_slug}}-keycloak:
    image: keycloak/keycloak:25.0
    hostname: {{cookiecutter.project_slug}}-keycloak
    container_name: {{cookiecutter.project_slug}}-keycloak
    networks:
      - {{cookiecutter.project_slug}}-network

    ports:
      - 8080:8080

    volumes:
      - ../db/keycloak:/opt/keycloak/data/import

    env_file:
      - .kc_env

    command: -v start-dev --import-realm

    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

    depends_on:
      - {{cookiecutter.project_slug}}-db
  {% endif %}

  shell:
    extends: {{cookiecutter.project_slug}}-server
    container_name: {{cookiecutter.project_slug}}-server-shell

    ports:
      - 8001:8000
      - 56781:5678
      - 8081:8080

    volumes:
      - ..:/project:delegated
      - /tmp:/tmp
      - ~/.ssh:/home/devel/.ssh

    command: "/usr/bin/tmux -L server"

    depends_on:
      {{cookiecutter.project_slug}}-db:
        condition: service_healthy
      {% if cookiecutter.use_redis == "y" %}
      {{cookiecutter.project_slug}}-redis
        condition: service_healthy
      {% endif %}
      {% if cookiecutter.use_keycloak == "y" %}
      {{cookiecutter.project_slug}}-keycloak
        condition: service_healthy
      {% endif %}

volumes:
  postgres-{{cookiecutter.project_slug}}-data:


networks:
  {{cookiecutter.project_slug}}-network:
    name: {{cookiecutter.project_slug}}-network
